name: Maven Publish

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: central
        server-username: CENTRAL_USERNAME
        server-password: CENTRAL_PASSWORD
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Publish to Maven Central
      run: mvn deploy
      env:
         CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
         CENTRAL_PASSWORD: ${{ secrets.CENTRAL_TOKEN }}
         GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
